---
name: NOT JAMES
author: James Ward <james@notjam.es>
url: http://notjam.es

timezone: "America/New_York"

contact:
 email: "rot13:znvygb:wnzrf@abgwnz.rf"
 github: "rot13://tvguho.pbz/vzabgwnzrf"
 twitter: "rot13://gjvggre.pbz/gehylabgwnzrf"

permalink: /blog/:year/:month/:day/:title.html

paginate: 10
paginate_path: "blog/page/:num"

highlighter: rouge
markdown: redcarpet

redcarpet:
 extensions:
  - no_intra_emphasis
  - fenced_code_blocks
  - autolink
  - strikethrough
  - superscript
  - tables
  - with_toc_data

gems:
 - jekyll-sitemap

sass:
 style: compressed
