name: NOT JAMES
markdown: redcarpet
highlighter: pygments

url: http://notjam.es

permalink: /blog/:year/:month/:day/:title.html

paginate: 10
paginate_path: "blog/page/:num"

contact:
 email: "rot13:znvygb:wnzrf@abgwnz.rf"
 github: "rot13://tvguho.pbz/vzabgwnzrf"

timezone: "America/New_York"
