on:
  push:
    branches:
      - gh-pages

name: build gatsby
jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install dependencies
        run: npm install

      - name: gatsby build
        run: npm run build

      - name: deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GITHUB_API_KEY }}
          BUILD_DIR: "public/"