on:
  push:
    branches:
      - main

name: build gatsby
jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependencies
        run: npm install

      - name: gatsby build
        run: npm run build

      - name: deploy to github pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: "public/"
